-- AfriLink Database Phase 2 migration — Notifications module only
-- Scope: notification (docs/04-database/database.md §10)
-- Database implementation only — no controllers, services, workers, or
-- WebSocket/push delivery (MVP notifications are REST-polled, ADR-004 §7).
--
-- AUTO-GENERATED section below was produced by:
--   npx prisma migrate diff --from-migrations ./migrations --to-schema schema.prisma --script
-- against the Phase 1 + Communities + Messaging migration history plus this
-- increment's schema.prisma changes, using a transient shadow database.
--
-- HISTORICAL NOTE (resolved — nothing to strip when regenerating):
-- When this migration was first generated, the raw diff also emitted:
--   ALTER TABLE "messaging"."conversations" DROP CONSTRAINT "conversations_direct_participant_a_id_fkey";
--   ALTER TABLE "messaging"."conversations" DROP CONSTRAINT "conversations_direct_participant_b_id_fkey";
-- Those two foreign keys were added by hand in
-- 20260918010000_add_messaging, and at the time schema.prisma did not model
-- them as relations, so Prisma treated them as drift and proposed dropping
-- them on every diff. Those two statements were left out of this file
-- because applying them would have silently removed a messaging integrity
-- guarantee (ON DELETE RESTRICT on the one-to-one pairing columns) and is
-- unrelated to Notifications. That drift has since been fixed at the source:
-- schema.prisma now declares Conversation.directParticipantA/B as relations
-- matching the existing constraints exactly, so the diff no longer proposes
-- any messaging change. Regenerating this section from
-- 20260914000000_init_phase1 + 20260918000000_add_communities +
-- 20260918010000_add_messaging now reproduces the statements below verbatim,
-- with no DROPs. This migration still does not touch the messaging schema.
--
-- HAND-ADDED section (clearly marked, at the bottom) contains the CHECK
-- constraints and the partial index Prisma's schema DSL cannot express —
-- each is called out in a comment in schema.prisma next to the model it
-- belongs to.
--
-- Additive only: every statement is CREATE SCHEMA/TABLE/INDEX or an ADD
-- CONSTRAINT/FOREIGN KEY scoped to the new `notification` schema. The only
-- references outward are foreign keys from the new tables to the existing
-- identity.users(id); no pre-existing table, column, index, or constraint
-- is altered or dropped.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "notification";

-- CreateTable
CREATE TABLE "notification"."notifications" (
    "id" UUID NOT NULL,
    "recipient_user_id" UUID NOT NULL,
    "actor_user_id" UUID,
    "type" TEXT NOT NULL,
    "target_type" TEXT,
    "target_id" UUID,
    "group_key" TEXT,
    "dedup_key" TEXT,
    "payload" JSONB,
    "read_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification"."preferences" (
    "user_id" UUID NOT NULL,
    "category" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL,
    "locale" TEXT,
    "quiet_hours_start" TEXT,
    "quiet_hours_end" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "preferences_pkey" PRIMARY KEY ("user_id","category","channel")
);

-- CreateIndex
CREATE INDEX "notifications_recipient_user_id_created_at_id_idx" ON "notification"."notifications"("recipient_user_id", "created_at" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "notifications_deleted_at_idx" ON "notification"."notifications"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "notifications_recipient_user_id_dedup_key_key" ON "notification"."notifications"("recipient_user_id", "dedup_key");

-- AddForeignKey
ALTER TABLE "notification"."notifications" ADD CONSTRAINT "notifications_recipient_user_id_fkey" FOREIGN KEY ("recipient_user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification"."notifications" ADD CONSTRAINT "notifications_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification"."preferences" ADD CONSTRAINT "preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================
-- HAND-ADDED
-- (not expressible in Prisma's schema DSL — each is called out in a
-- comment in schema.prisma; these do not come from, and cannot be
-- regenerated by, `prisma migrate diff`)
-- ============================================================

-- notification.notifications: nobody is notified of their own action —
-- matching the self-action CHECK pattern used for follows/friendships/
-- blocks/community.invitations/messaging.conversations. actor_user_id is
-- NULL for system-originated notifications, which the check permits.
ALTER TABLE "notification"."notifications"
    ADD CONSTRAINT "notifications_no_self_notify_check" CHECK ("actor_user_id" IS NULL OR "actor_user_id" <> "recipient_user_id");

-- notification.notifications: a polymorphic target is either fully
-- specified or absent — never a type with no id (or an id with no type).
ALTER TABLE "notification"."notifications"
    ADD CONSTRAINT "notifications_target_paired_check" CHECK (("target_type" IS NULL) = ("target_id" IS NULL));

-- notification.notifications: unread-count / unread-list support. Partial
-- (only live, unread rows) so it stays small and cheap even for users with
-- long notification histories; the full (recipient, created_at, id) index
-- above still serves the ordinary paginated list.
CREATE INDEX "notifications_unread_idx"
    ON "notification"."notifications"("recipient_user_id", "created_at" DESC, "id" DESC)
    WHERE "read_at" IS NULL AND "deleted_at" IS NULL;
